In [1]:
import os
import re
import pandas as pd
import numpy as np

In [2]:
total_tfidf_df_list = list()

for i in range(0,1095):
    t_index_list = []
    tfidf_list = []
    
    path = "./tf_idf_vector/" + str(i + 1) + ".txt"
    with open(path, 'r', encoding='utf-8') as file:
        # 跳過Header
        next(file)
        for line in file:
            parts = line.strip().split()
            if len(parts) == 2:
                t_index, tfidf = int(parts[0]), float(parts[1])
                t_index_list.append(t_index)
                tfidf_list.append(tfidf)

    single_doc_data = {'t_index': t_index_list, 'tf_idf': tfidf_list}
    single_doc = pd.DataFrame(single_doc_data)
    total_tfidf_df_list.append(single_doc)

In [3]:
total_tfidf_df_list[:500]

[     t_index    tf_idf
 0      11970  0.005025
 1       4970  0.003534
 2        338  0.002228
 3       5710  0.005692
 4       1955  0.003865
 ..       ...       ...
 120     7207  0.002693
 121     6102  0.005632
 122    10426  0.007297
 123     7561  0.008118
 124     7217  0.003042

 [125 rows x 2 columns],
      t_index    tf_idf
 0      11220  0.004213
 1       7217  0.015985
 2       7644  0.008873
 3      10798  0.009644
 4       8106  0.003673
 ..       ...       ...
 122     8648  0.006897
 123     9207  0.008293
 124      217  0.007109
 125     6521  0.006232
 126     2762  0.004239

 [127 rows x 2 columns],
      t_index    tf_idf
 0       8262  0.001675
 1      10377  0.006089
 2       6038  0.002125
 3       1713  0.003906
 4       8136  0.003735
 ..       ...       ...
 334     8449  0.002125
 335    11930  0.001468
 336     4749  0.002289
 337    10772  0.001762
 338     3762  0.002029

 [339 rows x 2 columns],
      t_index    tf_idf
 0      12208  0.019903
 1       2738  0.010932
 2       7497  0.032797
 3       7488  0.004286
 4       7123  0.007404
 ..       ...       ...
 96      8673  0.012121
 97     12137  0.010190
 98      3531  0.018302
 99      6324  0.013753
 100     7225  0.018302

 [101 rows x 2 columns],
      t_index    tf_idf
 0      12208  0.015395
 1       7497  0.021140
 2      11540  0.005943
 3      10544  0.006701
 4        946  0.004754
 ..       ...       ...
 129     4027  0.004190
 130     6766  0.004455
 131    10684  0.004660
 132     3634  0.004241
 133     3981  0.007712

 [134 rows x 2 columns],
      t_index    tf_idf
 0      11008  0.001978
 1       2455  0.003269
 2      11761  0.001782
 3       7217  0.000688
 4       6505  0.001713
 ..       ...       ...
 390     1713  0.001557
 391     3571  0.001399
 392     6607  0.001016
 393    11970  0.001137
 394     4970  0.000800

 [395 rows x 2 columns],
      t_index    tf_idf
 0       3418  0.003123
 1       1771  0.003096
 2       2463  0.004165
 3       2275  0.003888
 4      11178  0.007515
 ..       ...       ...
 314    11739  0.001743
 315     5832  0.002808
 316     7426  0.000706
 317     3993  0.001448
 318     2613  0.000743

 [319 rows x 2 columns],
      t_index    tf_idf
 0       9913  0.002154
 1       6743  0.029294
 2       4330  0.004092
 3         24  0.003519
 4       7926  0.003688
 ..       ...       ...
 310     9344  0.005590
 311     3646  0.003430
 312     6000  0.003806
 313    10638  0.004900
 314    11936  0.002162

 [315 rows x 2 columns],
      t_index    tf_idf
 0       9913  0.002154
 1       6743  0.029294
 2       4330  0.004092
 3         24  0.003519
 4       7926  0.003688
 ..       ...       ...
 310     9344  0.005590
 311     3646  0.003430
 312     6000  0.003806
 313    10638  0.004900
 314    11936  0.002162

 [315 rows x 2 columns],
     t_index    tf_idf
 0     12209  0.021921
 1      8259  0.003500
 2      9913  0.011048
 3      6743  0.053665
 4     11851  0.011788
 ..      ...       ...
 68    11770  0.012332
 69     5839  0.012077
 70     2876  0.010967
 71       87  0.018050
 72     8889  0.013564

 [73 rows x 2 columns],
      t_index    tf_idf
 0       7140  0.019157
 1      11412  0.003281
 2      10243  0.001914
 3       5501  0.030504
 4      10068  0.016714
 ..       ...       ...
 162     2447  0.003380
 163     9921  0.005079
 164      740  0.008613
 165     4648  0.005158
 166     5181  0.004832

 [167 rows x 2 columns],
     t_index    tf_idf
 0     12207  0.025040
 1      7497  0.016457
 2      6011  0.012061
 3      9654  0.020358
 4      2447  0.020573
 ..      ...       ...
 66     7475  0.005526
 67    10289  0.009741
 68     4065  0.013801
 69      758  0.004942
 70     7217  0.005300

 [71 rows x 2 columns],
     t_index    tf_idf
 0      7497  0.009811
 1      8382  0.011865
 2      2249  0.008688
 3     12208  0.047632
 4      8259  0.011441
 5      9913  0.024078
 6      6743  0.023393
 7      9747  0.009781
 8      9791  0.011738
 9      1252  0.025616
 10     5351  0.008961
 11     8264  0.015002
 12    10289  0.023228
 13     9221  0.032657
 14    11754  0.077934
 15     8452  0.030466
 16     7424  0.023903
 17     6579  0.046384
 18     3340  0.006991
 19     2443  0.033513
 20    10303  0.052293
 21     9142  0.026733
 22     8874  0.005593
 23     6942  0.043915
 24    12133  0.017897
 25    10246  0.013107
 26     3656  0.014854
 27     2137  0.013054
 28     6964  0.018569
 29    10799  0.021045
 30     2787  0.014568
 31     4104  0.032850
 32    11441  0.031248
 33     2205  0.022874
 34     9824  0.006496
 35     9220  0.011908
 36    11181  0.019014
 37     4138  0.014568
 38     9264  0.002265
 39     8247  0.011951
 40     7847  0.025390
 41     6362  0.027389
 42     4794  0.013945
 43     5393  0.020826
 44    11770  0.013438
 45     5839  0.013161
 46    10684  0.010814
 47     2613  0.004639
 48      704  0.008114
 49      831  0.028132
 50      963  0.013326
 51     3104  0.016655
 52     7174  0.015898
 53     8907  0.023889
 54     2166  0.017649
 55     9143  0.038967
 56      910  0.020218
 57     7217  0.006319,
      t_index    tf_idf
 0      12093  0.006692
 1       8326  0.007745
 2        910  0.002312
 3       9583  0.001073
 4       8278  0.002732
 ..       ...       ...
 356    10205  0.001978
 357     8247  0.001367
 358     8450  0.001132
 359    11918  0.002776
 360    10094  0.001347

 [361 rows x 2 columns],
     t_index    tf_idf
 0     12208  0.015352
 1      8259  0.014751
 2      9913  0.007761
 3      6743  0.045238
 4      7494  0.009623
 ..      ...       ...
 90    10387  0.013290
 91      966  0.014950
 92     8491  0.005860
 93     6102  0.007540
 94     2637  0.005910

 [95 rows x 2 columns],
     t_index    tf_idf
 0     12208  0.033172
 1     11022  0.018257
 2      9577  0.025863
 3      1713  0.019913
 4      9913  0.016769
 5      6743  0.048874
 6     12171  0.004955
 7      9196  0.013303
 8     10317  0.008394
 9      8760  0.017613
 10     2133  0.024093
 11     2682  0.015787
 12     5963  0.005972
 13    11912  0.008208
 14     3340  0.019474
 15    10786  0.020488
 16    10903  0.015112
 17    10401  0.019731
 18    12087  0.015896
 19    11138  0.009444
 20     3173  0.021902
 21     8187  0.018604
 22     8048  0.016467
 23     8378  0.054275
 24    10804  0.054275
 25     1131  0.020006
 26     9069  0.022394
 27      102  0.017147
 28     6403  0.008957
 29     1982  0.027398
 30     6758  0.031043
 31    11823  0.021439
 32     5569  0.018332
 33     4415  0.054275
 34     9067  0.054275
 35     9202  0.011301
 36     3342  0.025289
 37     2093  0.020689
 38     6535  0.010916
 39    10237  0.014916
 40    11220  0.013917
 41     9264  0.003155
 42     8685  0.016526
 43     3449  0.016176
 44    11784  0.013874
 45    10522  0.013147
 46     7497  0.013665
 47     1538  0.031466
 48     9371  0.004756
 49     9207  0.027398,
     t_index    tf_idf
 0      9562  0.033824
 1      8822  0.005329
 2     10798  0.018206
 3     10988  0.005507
 4     11817  0.015656
 ..      ...       ...
 82     3579  0.011765
 83     6361  0.012247
 84    10553  0.010390
 85     2366  0.007692
 86     2603  0.015656

 [87 rows x 2 columns],
      t_index    tf_idf
 0       9913  0.002096
 1       6743  0.022400
 2       4417  0.005501
 3      10909  0.009219
 4       2388  0.003425
 ..       ...       ...
 293     8566  0.002096
 294    10933  0.001560
 295     3857  0.001653
 296     8449  0.002708
 297     3173  0.002738

 [298 rows x 2 columns],
      t_index    tf_idf
 0       7332  0.018368
 1      10468  0.016857
 2       3885  0.020188
 3       9202  0.004164
 4       8686  0.005816
 ..       ...       ...
 110      368  0.003234
 111     6535  0.004022
 112     4395  0.007699
 113    11037  0.008113
 114     6799  0.016857

 [115 rows x 2 columns],
     t_index    tf_idf
 0     12208  0.018576
 1      6020  0.014385
 2      9849  0.016231
 3      1879  0.014019
 4      6232  0.017266
 5      8187  0.010418
 6     10988  0.010795
 7       670  0.019804
 8     10401  0.022098
 9      1982  0.030685
 10     6758  0.034768
 11     4322  0.011722
 12     8259  0.005950
 13     9913  0.018781
 14     6743  0.018246
 15      136  0.028747
 16     2682  0.017682
 17     8686  0.017682
 18     3340  0.032716
 19     1560  0.016760
 20      963  0.020788
 21    10433  0.026140
 22     7497  0.030610
 23     7771  0.015122
 24    10544  0.024258
 25     8566  0.018781
 26     4417  0.009857
 27    11851  0.020040
 28     2389  0.040788
 29     1508  0.009401
 30    10480  0.051246
 31     1454  0.021703
 32     3701  0.034768
 33      338  0.007218
 34     1955  0.012522
 35     1538  0.017621
 36    11770  0.020964
 37     5839  0.020532
 38    12207  0.023287
 39     2079  0.021326
 40     1889  0.018576
 41    12012  0.017094
 42    11784  0.015539
 43     9207  0.030685
 44     9589  0.013330
 45     7412  0.023172,
      t_index    tf_idf
 0       6535  0.003304
 1       4906  0.002888
 2       9493  0.004415
 3        274  0.007391
 4       6588  0.004359
 ..       ...       ...
 137     5797  0.016429
 138     8426  0.010596
 139     5559  0.007199
 140     7148  0.006594
 141     7217  0.002664

 [142 rows x 2 columns],
     t_index    tf_idf
 0     12208  0.025103
 1     10988  0.014587
 2      4417  0.026642
 3      9913  0.025380
 4      6743  0.073971
 5      8450  0.020871
 6       586  0.027081
 7     11855  0.049603
 8      6011  0.015158
 9      6758  0.046983
 10    10401  0.059725
 11     7426  0.009295
 12     9371  0.007199
 13     9561  0.036228
 14     6578  0.032619
 15     6535  0.016521
 16     7227  0.017915
 17     9488  0.021591
 18     2613  0.009779
 19     4286  0.018316
 20      230  0.040415
 21     3173  0.033149
 22     7425  0.012927
 23     8101  0.019272
 24     2210  0.024923
 25    10564  0.065874
 26     8106  0.018367
 27    11220  0.021063
 28      737  0.022073
 29     6437  0.061115
 30     2339  0.012087
 31     8640  0.022003
 32     4906  0.014440,
      t_index    tf_idf
 0       3519  0.005546
 1      12207  0.006193
 2       2443  0.006952
 3       8259  0.001582
 4       9913  0.002497
 ..       ...       ...
 262    10385  0.002105
 263     7516  0.002444
 264    11154  0.004235
 265     4027  0.002017
 266     5362  0.005035

 [267 rows x 2 columns],
      t_index    tf_idf
 0       9563  0.001813
 1       4417  0.006048
 2       5436  0.001277
 3       4703  0.002815
 4      11851  0.001537
 ..       ...       ...
 386     2795  0.002815
 387     4677  0.001687
 388     2507  0.004200
 389     7160  0.002396
 390     5142  0.001380

 [391 rows x 2 columns],
      t_index    tf_idf
 0       9563  0.006424
 1       4417  0.013393
 2       5436  0.004525
 3       4703  0.009974
 4      11851  0.005446
 ..       ...       ...
 136    10418  0.008739
 137     5845  0.014883
 138     1520  0.003622
 139     4757  0.006033
 140    10094  0.004994

 [141 rows x 2 columns],
     t_index    tf_idf
 0     12208  0.033172
 1       963  0.037122
 2     10433  0.046679
 3      7497  0.054661
 4      7771  0.027004
 5     10544  0.043317
 6      8566  0.033537
 7      4417  0.017603
 8     11851  0.035785
 9      2389  0.072836
 10     1454  0.038756
 11     3701  0.062085
 12     1955  0.022361
 13     1538  0.031466
 14     9371  0.009513
 15    12064  0.028620
 16     3340  0.058421
 17     2079  0.038082
 18     9264  0.006310
 19    12012  0.030526
 20    11784  0.027749
 21     9207  0.054795
 22     9399  0.040583
 23    10522  0.026294,
      t_index    tf_idf
 0      12208  0.008148
 1      10988  0.003156
 2       9563  0.003456
 3        704  0.001851
 4       8383  0.012194
 ..       ...       ...
 197    12034  0.008887
 198     2035  0.004906
 199    10094  0.005373
 200     7240  0.005963
 201    10848  0.005680

 [202 rows x 2 columns],
     t_index    tf_idf
 0     12207  0.052925
 1       704  0.028767
 2      8034  0.029079
 3       586  0.045545
 4      3352  0.089101
 5      1982  0.069739
 6      6758  0.079017
 7     11238  0.012375
 8      7497  0.034784
 9      8111  0.064371
 10    10582  0.067414
 11     9238  0.102785
 12     2185  0.054859
 13    10401  0.050223
 14      104  0.048259
 15     8259  0.013522
 16     9913  0.042684
 17     6743  0.041469
 18     6151  0.072375
 19      910  0.071683
 20     7217  0.022403
 21    12093  0.029637,
      t_index    tf_idf
 0      11238  0.001171
 1       6900  0.002608
 2        208  0.001556
 3       5871  0.025143
 4       9221  0.010956
 ..       ...       ...
 277     6138  0.002398
 278      149  0.002623
 279     3385  0.002138
 280     3570  0.002981
 281     9482  0.005242

 [282 rows x 2 columns],
      t_index    tf_idf
 0      11412  0.007868
 1      10243  0.006119
 2      12111  0.009790
 3       3634  0.008673
 4       9220  0.015743
 ..       ...       ...
 103     3696  0.005639
 104      226  0.004750
 105      338  0.002039
 106     4534  0.009702
 107     9258  0.008001

 [108 rows x 2 columns],
      t_index    tf_idf
 0      10008  0.019584
 1       8418  0.004368
 2       1572  0.009710
 3       3522  0.018971
 4      11995  0.012867
 ..       ...       ...
 144    11590  0.007987
 145     1682  0.004084
 146    10194  0.006539
 147    11170  0.005736
 148      186  0.005705

 [149 rows x 2 columns],
     t_index    tf_idf
 0      9913  0.013415
 1      6743  0.013033
 2      8101  0.020374
 3      3461  0.034667
 4      6360  0.010611
 5      1982  0.021918
 6      6756  0.039066
 7     10068  0.013514
 8     11910  0.011306
 9      1295  0.014201
 10     7475  0.003671
 11     1047  0.020691
 12    10401  0.047354
 13     5978  0.019026
 14     3736  0.022335
 15     3173  0.017521
 16    12207  0.016634
 17     8259  0.004250
 18     8187  0.007441
 19     5209  0.030075
 20     7217  0.014082
 21      199  0.027749
 22     9264  0.010096
 23    11180  0.033435
 24    10008  0.015038
 25     5814  0.025842
 26     2113  0.020380
 27     4417  0.007041
 28     3903  0.009763
 29     2613  0.005169
 30    10909  0.019667
 31     3342  0.020231
 32    10543  0.018558
 33     1013  0.061038
 34    10404  0.027507
 35      450  0.019026
 36    10768  0.016887
 37     3694  0.019803
 38     6758  0.024834
 39     8760  0.028181
 40     6022  0.010705
 41     2122  0.022318
 42     1900  0.018672
 43      586  0.014314
 44     4347  0.011630
 45     7097  0.011856
 46     8512  0.019803
 47     6011  0.008012
 48     8224  0.034819
 49    10279  0.034819
 50      487  0.015167
 51     8901  0.014911
 52     7151  0.017427
 53    11066  0.013982
 54     2063  0.008802
 55     4794  0.007770,
      t_index    tf_idf
 0       9913  0.004429
 1       6743  0.034427
 2       8101  0.010091
 3       3461  0.011447
 4       6360  0.007007
 ..       ...       ...
 151     8396  0.008657
 152    11723  0.004784
 153     2961  0.009620
 154     2749  0.005008
 155    11585  0.010666

 [156 rows x 2 columns],
      t_index    tf_idf
 0       9913  0.002174
 1       6743  0.029566
 2       8101  0.008253
 3       3461  0.005617
 4       6360  0.005158
 ..       ...       ...
 276     5302  0.002501
 277     8889  0.002669
 278     7595  0.003975
 279     7773  0.002920
 280     1763  0.004625

 [281 rows x 2 columns],
      t_index    tf_idf
 0       9913  0.002257
 1       6743  0.026317
 2       8101  0.006857
 3       3461  0.002917
 4       6360  0.003571
 ..       ...       ...
 285    10673  0.001212
 286     8160  0.002574
 287       75  0.002111
 288    11785  0.002948
 289    10246  0.002458

 [290 rows x 2 columns],
     t_index    tf_idf
 0     10401  0.033997
 1      8382  0.028476
 2      9561  0.041244
 3      8259  0.004577
 4      9913  0.014447
 5      6743  0.028071
 6       488  0.011495
 7      5334  0.028667
 8     12208  0.014290
 9     10903  0.013020
 10     4255  0.016695
 11     1686  0.017077
 12     7769  0.010142
 13      963  0.015991
 14    10988  0.008303
 15     6435  0.019516
 16     1879  0.010784
 17     2366  0.011598
 18     4937  0.010603
 19    10461  0.025253
 20     7948  0.028235
 21     1743  0.011598
 22     2439  0.015665
 23     7423  0.028235
 24     3251  0.011773
 25     7497  0.011773
 26     6011  0.008628
 27     5978  0.020490
 28     4047  0.021787
 29     2110  0.026418
 30      313  0.018186
 31    11784  0.011953
 32    10696  0.039420
 33     5963  0.005145
 34     6900  0.009330
 35     8261  0.010693
 36     3340  0.008389
 37     8101  0.010970
 38     6973  0.010970
 39     1982  0.047208
 40     6756  0.021036
 41     3312  0.011881
 42     4322  0.009017
 43     6758  0.053489
 44     8921  0.042129
 45     8326  0.027087
 46     2524  0.015057
 47    10543  0.019985
 48    10243  0.004166
 49     7670  0.026418
 50     3342  0.021787
 51    11562  0.072014
 52     1649  0.014136
 53     5144  0.022282
 54     9113  0.024739
 55     1097  0.037498
 56      102  0.014773
 57     9562  0.016999,
     t_index    tf_idf
 0     12208  0.029026
 1     11022  0.031949
 2      2357  0.013266
 3      4840  0.044582
 4      2366  0.023558
 5       446  0.062438
 6      7769  0.020600
 7      7904  0.040351
 8      8261  0.021719
 9      3340  0.034079
 10      341  0.035011
 11     6566  0.032618
 12     9196  0.023280
 13    12181  0.025685
 14     4167  0.045975
 15     5802  0.026447
 16     2339  0.013976
 17      670  0.030944
 18     4347  0.025441
 19     9913  0.029345
 20     6743  0.057019
 21    10958  0.021660
 22     3634  0.023987
 23     6499  0.044582
 24     8566  0.029345
 25     7497  0.023914
 26     1889  0.029026
 27     6232  0.026979
 28    10289  0.028309,
      t_index    tf_idf
 0       8768  0.003726
 1       9913  0.001418
 2       6743  0.008269
 3       1295  0.004505
 4      11770  0.001583
 ..       ...       ...
 393     3573  0.001625
 394     3419  0.000902
 395      946  0.001300
 396     7207  0.000659
 397     1549  0.001884

 [398 rows x 2 columns],
     t_index    tf_idf
 0     12208  0.016888
 1      4840  0.025939
 2      2366  0.013706
 3     10988  0.019626
 4      5381  0.039897
 5      7769  0.011986
 6      8686  0.016074
 7      8261  0.012637
 8      3340  0.019828
 9      6973  0.012965
 10     1520  0.024236
 11     7497  0.041741
 12    10544  0.011026
 13     4016  0.008653
 14     8101  0.012965
 15      758  0.008357
 16     9520  0.027653
 17    10402  0.042554
 18     1982  0.027896
 19     6756  0.024860
 20     9196  0.027089
 21     8874  0.007932
 22    10243  0.004923
 23     7217  0.008961
 24      199  0.017659
 25     1617  0.014755
 26     1361  0.017726
 27     1889  0.016888
 28    11771  0.046587
 29     5839  0.018665
 30     2660  0.018978
 31    12020  0.020089
 32     8259  0.005409
 33     9913  0.017074
 34     6743  0.033175
 35       89  0.023619
 36     2682  0.016074
 37     6022  0.013625
 38     7425  0.008697
 39     6011  0.010197
 40     9264  0.003212
 41     3776  0.018146
 42    12111  0.006301
 43     1467  0.025381
 44    10958  0.006301
 45     4417  0.008961
 46     2388  0.027896
 47     3017  0.041114,
      t_index    tf_idf
 0       7797  0.001955
 1      11912  0.001006
 2       4620  0.002078
 3      12207  0.002548
 4       2169  0.003169
 ..       ...       ...
 255      470  0.004563
 256    10094  0.002011
 257    10848  0.002125
 258    11514  0.003904
 259    11922  0.002952

 [260 rows x 2 columns],
     t_index    tf_idf
 0      2226  0.023407
 1      2366  0.017330
 2     12208  0.010676
 3      8875  0.018302
 4       446  0.022966
 ..      ...       ...
 63    11138  0.006079
 64    11110  0.013518
 65      910  0.018127
 66     7207  0.005015
 67     6904  0.034936

 [68 rows x 2 columns],
      t_index    tf_idf
 0       1237  0.005456
 1       7734  0.005074
 2       1607  0.002376
 3        506  0.005456
 4       4745  0.005020
 ..       ...       ...
 203     5710  0.002820
 204     7490  0.002506
 205     6068  0.003247
 206     9196  0.002278
 207     7502  0.004429

 [208 rows x 2 columns],
     t_index    tf_idf

In [4]:
total_tfidf_df_list[0]

     t_index    tf_idf
0      11970  0.005025
1       4970  0.003534
2        338  0.002228
3       5710  0.005692
4       1955  0.003865
..       ...       ...
120     7207  0.002693
121     6102  0.005632
122    10426  0.007297
123     7561  0.008118
124     7217  0.003042

[125 rows x 2 columns]

In [5]:
total_tfidf_df_list[0]['tf_idf']

0      0.005025
1      0.003534
2      0.002228
3      0.005692
4      0.003865
         ...
120    0.002693
121    0.005632
122    0.007297
123    0.008118
124    0.003042
Name: tf_idf, Length: 125, dtype: float64

In [6]:
# 計算其unit vector
def norm(tfidf_List):
    norm_vector = sum(tfidf ** 2 for tfidf in tfidf_List) ** 0.5
    return norm_vector

In [7]:
def cosine(doc1_df, doc2_df):
    # 以t_index做outer merge
    merged_df = pd.merge(doc1_df, doc2_df, on='t_index', how='outer').fillna(0)
    
    # 轉換為unit vector
    doc1_norm = norm(merged_df['tf_idf_x'].to_list())
    doc2_norm = norm(merged_df['tf_idf_y'].to_list())
    
    # 计算cosine similarity
    similarity = np.dot(merged_df['tf_idf_x']/doc1_norm, merged_df['tf_idf_y']/doc2_norm)
    
    return similarity

In [8]:
column_c = list(range(0,1095))
row_c = list(range(0,1095))

In [9]:
AS = cosine(total_tfidf_df_list[0],total_tfidf_df_list[17])
AS

0.3341522060559187

In [10]:
C = pd.DataFrame(columns=column_c, index=row_c)
for i in range(0,1095):
    for j in range(i,1095):
        C.iat[i,j] = cosine(total_tfidf_df_list[i],total_tfidf_df_list[j])
        C.iat[j,i] = C.iat[i,j]

In [17]:
C

,0,1,2,3,4,5,6,7,8,9,...,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094
0,1.0,0.202227,0.302513,0.218558,0.262001,0.245064,0.293049,0.223558,0.223558,0.275628,...,0.024217,0.020864,0.03397,0.016939,0.04833,0.021772,0.025764,0.034973,0.029627,0.048898
1,0.202227,1.0,0.210836,0.233014,0.25783,0.185268,0.20792,0.10343,0.10343,0.182735,...,0.010055,0.004837,0.02785,0.002382,0.035186,0.000689,0.011381,0.027174,0.011868,0.022876
2,0.302513,0.210836,1.0,0.337723,0.312437,0.401215,0.397163,0.223261,0.223261,0.301228,...,0.047245,0.032326,0.047048,0.01605,0.039024,0.017432,0.033008,0.044105,0.022571,0.03951
3,0.218558,0.233014,0.337723,1.0,0.327056,0.210253,0.32045,0.109706,0.109706,0.205004,...,0.006545,0.006867,0.026045,0.008838,0.003713,0.00202,0.013693,0.020582,0.016818,0.02461
4,0.262001,0.25783,0.312437,0.327056,1.0,0.321078,0.298253,0.187557,0.187557,0.265726,...,0.014637,0.03588,0.039239,0.048166,0.031589,0.040304,0.018786,0.021576,0.017846,0.044201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,0.021772,0.000689,0.017432,0.00202,0.040304,0.016327,0.025611,0.015769,0.015769,0.013655,...,0.091536,0.090693,0.283405,0.270455,0.104272,1.0,0.074116,0.048771,0.196541,0.01654
1091,0.025764,0.011381,0.033008,0.013693,0.018786,0.067798,0.031362,0.023103,0.023103,0.009864,...,0.042592,0.033986,0.123089,0.038774,0.072823,0.074116,1.0,0.054048,0.057026,0.024213
1092,0.034973,0.027174,0.044105,0.020582,0.021576,0.053387,0.037447,0.037518,0.037518,0.014907,...,0.052095,0.047025,0.147413,0.055245,0.119641,0.048771,0.054048,1.0,0.132541,0.021064
1093,0.029627,0.011868,0.022571,0.016818,0.017846,0.018985,0.028909,0.011043,0.011043,0.039701,...,0.055822,0.062793,0.218365,0.251933,0.176973,0.196541,0.057026,0.132541,1.0,0.019183
1094,0.048898,0.022876,0.03951,0.02461,0.044201,0.045526,0.036347,0.027485,0.027485,0.021838,...,0.023248,0.019876,0.040885,0.002636,0.008939,0.01654,0.024213,0.021064,0.019183,1.0

In [12]:
def sim_matrix(similarity_matrix, cluster1_id, cluster2_id):
    # 確保其收到的資料格式為int
    cluster1_id = int(cluster1_id)
    cluster2_id = int(cluster2_id)
    
    # 使用廣播找出兩個索引對應的最小相似度值
    similarity_matrix[cluster1_id, :] = np.minimum(similarity_matrix[cluster1_id, :], similarity_matrix[cluster2_id, :])
    similarity_matrix[:, cluster1_id] = similarity_matrix[cluster1_id, :]  # 利用對稱性更新列
    similarity_matrix[cluster1_id, cluster1_id] = -np.inf  # 設定 cluster1 內部的值為負無窮大
    
    # 將 cluster2 對應的行和列設為負無窮大，表示已經合併
    similarity_matrix[cluster2_id, :] = -np.inf
    similarity_matrix[:, cluster2_id] = -np.inf

In [13]:
def max_pos(test_C):
    max_position = np.unravel_index(np.argmax(test_C), test_C.shape) 
    return max_position

In [14]:
def apply_HAC(clusters, k):

    while k < len(test_C):
        k_max = max(max_pos(test_C))  
        k_min = min(max_pos(test_C))  
        clusters[k_min] += clusters[k_max] 
        clusters[k_max] = []  
        sim_matrix(test_C, k_min, k_max)  # 更新similarity matrix
        k += 1
    
    return clusters

In [15]:
def write_file(cluster, k):
    file_name = f"./{k}.txt"
    with open(file_name, "w") as f:
        for group in cluster:
            if group:
                
                f.write('\n')
                f.write('\n'.join(map(str, sorted(group))))  
                f.write('\n')

In [16]:
# 分為8、13、20群
for k in [8, 13, 20]:
    output_k = k
    copy_C = C.copy()
    test_C = copy_C.to_numpy()
    np.fill_diagonal(test_C, 0)  # 將sim matrix對角線值設為零

    clusters = [[i + 1] for i in range(len(test_C))]  # 將每個文章都分為一個cluster

    clusters = apply_HAC(clusters, k)
    
    clusters = [group for group in clusters]  # 去除空的cluster

    for group in clusters:
        group.sort()  # 對每個群組的文章id進行排序

    # 寫入
    write_file(clusters, output_k)